
name: Agent CI (Inner Loop)
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  quick-build:
    runs-on: [ self-hosted, ue5, windows ]
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Link plugin into Sandbox
        run: |
          & ./Build/Scripts/Link-PluginIntoSandbox.ps1

      - name: Setup UE
        run: |
          & ./Build/Scripts/Setup-UE.ps1 -UEPath 'C:\Program Files\Epic Games\UE_5.6'

      - name: Build plugin (Win64)
        run: |
          $uplugin = Join-Path $PWD 'Plugins\SamplePlugin\SamplePlugin.uplugin'
          $outDir  = Join-Path $PWD 'Artifacts\Win64'
          & ./Build/Scripts/Build-Plugin.ps1 `
            -UEPath 'C:\Program Files\Epic Games\UE_5.6' `
            -PluginUPluginPath $uplugin `
            -OutDir $outDir `
            -TargetPlatforms @('Win64')
