name: CI
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, ready_for_review ]
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-test:
    # Only run on non-draft PRs for PR events, or always for push/manual triggers
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: [ self-hosted, ue5, windows ]
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Link plugin into Sandbox
        run: |
          & ./Build/Scripts/Link-PluginIntoSandbox.ps1
      - name: Setup UE
        run: |
          & ./Build/Scripts/Setup-UE.ps1 -UEPath "C:\Program Files\Epic Games\UE_5.6"
      - name: Build plugin (Win64)
        run: |
          & ./Build/Scripts/Build-Plugin.ps1 `
            -UEPath "C:\Program Files\Epic Games\UE_5.6" `
            -PluginUPluginPath "$PWD\Plugins\SamplePlugin\SamplePlugin.uplugin" `
            -OutDir "$PWD\Artifacts\Win64" `
            -TargetPlatforms @("Win64")
      - name: Run automation tests
        run: |
          & ./Build/Scripts/Run-AutomationTests.ps1 `
            -UEPath "C:\Program Files\Epic Games\UE_5.6" `
            -ProjectFile "$PWD\ProjectSandbox\ProjectSandbox.uproject" `
            -TestFilter "SamplePlugin.*" `
            -ResultsDir "$PWD\Artifacts\Tests"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.run_id) || format('ci-{0}', github.run_id) }}
          path: Artifacts/**
