name: Nightly

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  checks: write

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

env:
  UE_ROOT: 'C:\Program Files\Epic Games\UE_5.6'

jobs:
  win-gauntlet-nullrhi:
    if: github.repository != 'lifelike-and-believable/ue-plugin-template'
    runs-on: [ self-hosted, ue5, windows ]

    steps:
      - name: Checkout (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          submodules: recursive
      - name: Link plugin into Sandbox (optional)
        run: |
          if (Test-Path ./Build/Scripts/Link-PluginIntoSandbox.ps1) { & ./Build/Scripts/Link-PluginIntoSandbox.ps1 }
        shell: powershell

      - name: Locate plugin (.uplugin)
        id: find
        shell: powershell
        run: |
          $uplugin = Get-ChildItem -Path $PWD -Recurse -Filter *.uplugin | Select-Object -First 1
          if (-not $uplugin) {
            Write-Error "No .uplugin found in repository."
          }
          "plugin_path=$($uplugin.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "plugin_dir=$($uplugin.DirectoryName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "plugin_name=$($uplugin.BaseName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "Using plugin: $($uplugin.FullName)"

      - name: Build plugin (Win64)
        shell: powershell
        run: |
          $uat = Join-Path $env:UE_ROOT 'Engine\Build\BatchFiles\RunUAT.bat'
          $pkg = Join-Path $env:RUNNER_TEMP 'PluginPackage'
          New-Item -ItemType Directory -Force -Path $pkg | Out-Null
          & "$uat" BuildPlugin `
            -Plugin="${{ steps.find.outputs.plugin_path }}" `
            -Package="$pkg" `
            -TargetPlatforms=Win64 `
            -Rocket
      - name: Run Gauntlet (NullRHI)
        shell: powershell
        run: |
          & ./Build/Scripts/Run-Gauntlet.ps1 `
            -UEPath "$env:UE_ROOT" `
            -ProjectFile "$PWD\ProjectSandbox\ProjectSandbox.uproject" `
            -GauntletConfigs @("SamplePluginTests") `
            -OutputDir "$PWD\Artifacts\Gauntlet_NullRHI" `
            -NullRHI

      - name: Upload plugin package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find.outputs.plugin_name }}-Nightly-Win64
          path: ${{ runner.temp }}/PluginPackage

      - name: Upload Gauntlet results
        uses: actions/upload-artifact@v4
        with:
          name: Gauntlet-NullRHI-Results
          path: Artifacts/Gauntlet_NullRHI
          if-no-files-found: ignore
